### ISSUE TITLE
Getting issue in integrating this plugin template with the foreman

### ISSUE THREAD

**Issue by chetu-sachin** [theforeman/foreman_plugin_template#46]
![Screenshot from 2023-09-27 17-26-47](https://github.com/theforeman/foreman_plugin_template/assets/61280306/e989efb5-260c-4fed-83ea-a9dff526ac4b)
![Screenshot from 2023-09
![Screenshot from 2023-09-28 22-41-18](https://github.com/theforeman/foreman_plugin_template/assets/61280306/bc2410c7-b8ec-4fb6-a2d6-4080ae29f343)

![Screenshot from 2023-09-27 17-51-52](https://github.com/theforeman/foreman_plugin_template/assets/61280306/f1ab7443-78c3-4d20-9ec8-b0e0b5b91ac6)
-27 17-28-35](https://github.com/theforeman/foreman_plugin_template/assets/61280306/6936450d-f686-41fe-86b9-098e12a0ca68)

We're getting issue in integrating this plugin template with the foreman. We added plugin in /usr/share/foreman/plugins directory and added gem and it's path in /usr/share/foreman/bundler.d/Gemfile.local.rb. We did bundle install, foreman-rake db:migrate and foreman-rake db:seed but getting an error undefined local variable or method `register_gettext' for ForemanPluginTemplate::Engine:Class

When we commented this line in engine.rb foreman installer is working fine but UI shows something is went wrong. We have attached screenshots for reference. Kindly suggest something needful.

**Comment by ekohl** [comment]
@evgeni also found this and submitted https://github.com/theforeman/foreman_plugin_template/pull/50 so it should now work in the latest template.
